steps:

    #Build
  - name: 'docker'
    args: ['build', '-t', 'app', '.']

    #Run Migrations
  - name: 'docker'
    args: ['run', 'app', 'python3', 'manage.py', 'migrate']

  - name: 'docker'
    args: ['run', 'app', 'python3', 'manage.py', 'test']